/**
 * University of La Laguna
 * School of Engineering and Technology
 * Degree in Computer Engineering
 * Final Degree Project (TFG)
 *
 * @author Fabián González Lence <alu0101549491@ull.edu.es>
 * @since March 17, 2026
 * @file domain/enumerations/notification-type.ts
 * @desc Enumeration defining the types of notifications generated by the system.
 * @see {@link https://github.com/alu0101549491/TFG-Fabian-Gonzalez-Lence/tree/main/projects/5-TennisTournamentManager}
 */

/**
 * Represents the type/category of a system notification.
 */
export enum NotificationType {
  /** Registration has been confirmed. */
  REGISTRATION_CONFIRMED = 'REGISTRATION_CONFIRMED',
  /** A match has been scheduled. */
  MATCH_SCHEDULED = 'MATCH_SCHEDULED',
  /** A result has been entered for a match. */
  RESULT_ENTERED = 'RESULT_ENTERED',
  /** The order of play has been published. */
  ORDER_OF_PLAY_PUBLISHED = 'ORDER_OF_PLAY_PUBLISHED',
}
