/**
 * University of La Laguna
 * School of Engineering and Technology
 * Degree in Computer Engineering
 * Final Degree Project (TFG)
 *
 * @author Fabián González Lence <alu0101549491@ull.edu.es>
 * @since April 24, 2026
 * @file backend/src/infrastructure/database/migrations/014-add-is-auto-generated.ts
 * @desc Database migration to add isAutoGenerated column to phases table.
 * @see {@link https://github.com/alu0101549491/TFG-Fabian-Gonzalez-Lence/tree/main/projects/5-TennisTournamentManager}
 * @see {@link https://typescripttutorial.net}
 */

import {MigrationInterface, QueryRunner} from 'typeorm';

/**
 * Adds isAutoGenerated boolean column to phases table.
 * 
 * - Adds isAutoGenerated column (default: false)
 * - Sets isAutoGenerated=true for phases with phaseType IN ('MAIN', 'CONSOLATION')
 * - Manually created phases with phaseType='QUALIFYING' or 'CUSTOM' remain false
 */
export class AddIsAutoGenerated1745514000000 implements MigrationInterface {
  public name = 'AddIsAutoGenerated1745514000000';

  /**
   * Sets isAutoGenerated for existing phases based on phaseType.
   *
   * @param queryRunner - TypeORM query runner
   */
  public async up(queryRunner: QueryRunner): Promise<void> {
    // Column already exists (added by TypeORM), just update existing phases

    // Set isAutoGenerated=true for bracket-generated MAIN phases
    await queryRunner.query(`
      UPDATE "phases" 
      SET "isAutoGenerated" = true 
      WHERE "phaseType" = 'MAIN'
    `);

    // Set isAutoGenerated=true for consolation draw phases
    await queryRunner.query(`
      UPDATE "phases" 
      SET "isAutoGenerated" = true 
      WHERE "phaseType" = 'CONSOLATION'
    `);

    console.log('✅ Migration 014: Set isAutoGenerated for existing bracket phases');
  }

  /**
   * Removes isAutoGenerated column.
   *
   * @param queryRunner - TypeORM query runner
   */
  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE "phases"
      DROP COLUMN "isAutoGenerated"
    `);

    console.log('✅ Migration 014 (down): Removed isAutoGenerated column');
  }
}
