/**
 * University of La Laguna
 * School of Engineering and Technology
 * Degree in Computer Engineering
 * Final Degree Project (TFG)
 *
 * @author Fabián González Lence <alu0101549491@ull.edu.es>
 * @since April 10, 2026
 * @file src/presentation/pages/phases/phase-management.component.ts
 * @desc Component for multi-phase tournament management (linking, qualifiers, consolation).
 * @see {@link https://github.com/alu0101549491/TFG-Fabian-Gonzalez-Lence/tree/main/projects/5-TennisTournamentManager}
 * @see {@link https://typescripttutorial.net}
 */

import {Component, OnInit, inject, signal, computed} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
import {ActivatedRoute, Router, RouterModule} from '@angular/router';
import {PhaseService} from '../../../application/services/phase.service';
import {TournamentService} from '../../../application/services/tournament.service';
import {BracketService} from '../../../application/services/bracket.service';
import {RegistrationService} from '../../../application/services/registration.service';
import {PartnerInvitationService} from '../../../infrastructure/services/partner-invitation.service';
import {CategoryService} from '../../../application/services/category.service';
import {type PhaseDto, type TournamentDto, type BracketDto, type RegistrationDto} from '../../../application/dto';
import {type CategoryDto} from '../../../application/dto/category.dto';
import {AuthStateService, TournamentStateService} from '@presentation/services';
import {UserRepositoryImpl} from '../../../infrastructure/repositories/user.repository';
import templateHtml from './phase-management.component.html?raw';
import styles from './phase-management.component.css?raw';

/**
 * Interface for phase selection options in dropdowns.
 */
interface PhaseOption {
  phaseId: string;
  phaseName: string;
  bracketId: string;
  bracketName: string;
  tournamentId: string;
  tournamentName: string;
  tournamentType: string; // 'SINGLES' or 'DOUBLES'
  displayLabel: string;
  categoryId?: string;
}

/**
 * Interface for participant selection options in Lucky Loser dropdown.
 */
interface ParticipantOption {
  participantId: string;
  participantName: string;
  registrationId: string;
  seedNumber: number | null;
  acceptanceType: string;
  displayLabel: string;
}

/**
 * Interface representing a phase with its bracket and link information for the Overview tab.
 */
interface PhaseInfo {
  phaseId: string;
  phaseName: string;
  bracketId: string;
  bracketName: string;
  bracketType: string;
  matchCount: number;
  isCompleted: boolean;
  nextPhaseId: string | null;
  sequenceOrder: number;
  categoryId?: string;
  phaseType: string;
  isAutoGenerated?: boolean;
}

/**
 * Phase Management Component for tournament administrators.
 *
 * Administrative interface for multi-phase tournament operations:
 * - Link qualifying rounds to main draws
 * - Advance top qualifiers from Round Robin
 * - Create consolation brackets
 * - Promote Lucky Losers when participants withdraw
 *
 * **Access**: TOURNAMENT_ADMIN, SYSTEM_ADMIN only
 *
 * @example
 * Route: /tournaments/:tournamentId/phases
 */
@Component({
  selector: 'app-phase-management',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  template: templateHtml,
  styles: [styles],
})
export class PhaseManagementComponent implements OnInit {
  private readonly phaseService = inject(PhaseService);
  private readonly tournamentService = inject(TournamentService);
  private readonly bracketService = inject(BracketService);
  private readonly registrationService = inject(RegistrationService);
  private readonly partnerInvitationService = inject(PartnerInvitationService);
  private readonly userRepository = inject(UserRepositoryImpl);
  private readonly categoryService = inject(CategoryService);
  private readonly authState = inject(AuthStateService);
  protected readonly tournamentStateService = inject(TournamentStateService);
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);

  /** Current tournament ID from route */
  protected tournamentId = signal<string | null>(null);

  /** Current tournament details */
  protected tournament = signal<any>(null);

  /** Available phases in the tournament */
  protected phases = signal<PhaseDto[]>([]);

  /** All available phase options across all tournaments */
  protected allPhaseOptions = signal<PhaseOption[]>([]);

  /** Filtered source phase options (only from current tournament) */
  protected sourcePhaseOptions = signal<PhaseOption[]>([]);

  /** Filtered target phase options (only from tournaments with admin access) */
  protected targetPhaseOptions = signal<PhaseOption[]>([]);

  /** Withdrawable participants (ACCEPTED players who can be withdrawn for Lucky Loser) */
  protected withdrawableParticipants = signal<ParticipantOption[]>([]);

  /** Loading state */
  protected isLoading = signal<boolean>(true);

  /** Operation in progress */
  protected isProcessing = signal<boolean>(false);

  /** Error message */
  protected error = signal<string | null>(null);

  /** Success message */
  protected success = signal<string | null>(null);

  /** Active tab for operations */
  protected activeTab = signal<'overview' | 'link' | 'advance' | 'consolation' | 'lucky-loser'>('overview');

  /** All phases across all brackets for the current tournament (for Overview tab) */
  protected currentTournamentPhases = signal<PhaseInfo[]>([]);

  /**
   * Set of phase IDs that are referenced as consolation targets (`nextPhaseId`) by another phase.
   * Used to split phases into main-draw and consolation columns in the overview diagram.
   */
  protected readonly consolationPhaseIds = computed<Set<string>>(() => {
    const ids = new Set<string>();
    for (const phase of this.currentTournamentPhases()) {
      if (phase.nextPhaseId) ids.add(phase.nextPhaseId);
    }
    return ids;
  });

  /** Phases that belong to the main draw (i.e. not targeted as a consolation phase, and not qualifying). */
  protected readonly mainFlowPhases = computed<PhaseInfo[]>(() =>
    this.currentTournamentPhases().filter(p =>
      !this.consolationPhaseIds().has(p.phaseId) && p.phaseType !== 'QUALIFYING'
    )
  );

  /** Phases that are consolation targets (referenced by another phase's `nextPhaseId`). */
  protected readonly consolationFlowPhases = computed<PhaseInfo[]>(() =>
    this.currentTournamentPhases().filter(p => this.consolationPhaseIds().has(p.phaseId))
  );

  /**
   * Paired view of main-draw phases with their optional consolation counterpart.
   * Used to render the cross-draw flow diagram with horizontal arrows.
   *
   * @returns Array of `{main, consolation}` pairs in sequenceOrder.
   */
  protected readonly phasePairs = computed<Array<{main: PhaseInfo; consolation: PhaseInfo | null}>>(() => {
    const consolationMap = new Map<string, PhaseInfo>();
    for (const c of this.consolationFlowPhases()) {
      consolationMap.set(c.phaseId, c);
    }
    return this.mainFlowPhases().map(main => ({
      main,
      consolation: main.nextPhaseId ? (consolationMap.get(main.nextPhaseId) ?? null) : null,
    }));
  });

  /** Qualifying phases sorted by sequenceOrder (fed into the main draw). */
  protected readonly qualifyingPhases = computed<PhaseInfo[]>(() =>
    this.currentTournamentPhases()
      .filter(p => p.phaseType === 'QUALIFYING')
      .sort((a, b) => a.sequenceOrder - b.sequenceOrder)
  );

  /**
   * Combined rows for the 5-column flow diagram.
   * Qualifying phases are shown in reverse order so the last qualifying phase
   * (the final) appears at the top, aligned with the first main draw phase.
   *
   * @returns Array of `{pair, qual}` where either can be null.
   */
  protected readonly diagramRows = computed<Array<{pair: {main: PhaseInfo; consolation: PhaseInfo | null} | null; qual: PhaseInfo | null}>>(() => {
    const pairs = this.phasePairs();
    const quals = this.qualifyingPhases();
    const count = Math.max(pairs.length, quals.length);
    return Array.from({length: count}, (_, i) => ({
      pair: i < pairs.length ? pairs[i] : null,
      qual: i < quals.length ? quals[quals.length - 1 - i] : null,
    }));
  });

  /** Available tournament categories (for Create Phase modal) */
  protected tournamentCategories = signal<CategoryDto[]>([]);

  /** Whether the Create Phase modal is open */
  protected showCreateModal = signal(false);

  /** Create phase form state */
  protected createForm = signal({
    phaseName: '',
    phaseType: 'CUSTOM' as 'QUALIFYING' | 'MAIN' | 'CONSOLATION' | 'CUSTOM',
    categoryId: '',
    bracketType: 'SINGLE_ELIMINATION' as 'SINGLE_ELIMINATION' | 'ROUND_ROBIN' | 'MATCH_PLAY',
  });

  // Form models for each operation
  protected linkForm = signal({
    sourcePhaseId: '',
    targetPhaseId: '',
  });

  protected advanceForm = signal({
    sourcePhaseId: '',
    targetPhaseId: '',
    qualifierCount: 2, // Default to 2, will be adjusted based on tournament type
    categoryId: '',
  });

  protected consolationForm = signal({
    mainPhaseId: '',
    categoryId: '',
    eliminationRound: 1,
    consolationPhaseId: '', // Track created consolation phase for population
  });

  protected luckyLoserForm = signal({
    withdrawnParticipantId: '',
    phaseId: '',
    categoryId: '',
  });

  /**
   * Initializes component by checking admin permissions and loading data.
   */
  public ngOnInit(): void {
    this.checkAdminAccess();
    this.loadTournamentData();
  }

  /**
   * Check if current user has admin privileges.
   */
  private checkAdminAccess(): void {
    const currentUser = this.authState.getCurrentUser();

    if (!currentUser) {
      this.router.navigate(['/login']);
      return;
    }

    const role = currentUser.role;
    if (role !== 'SYSTEM_ADMIN' && role !== 'TOURNAMENT_ADMIN') {
      this.error.set('Access denied: This page is for administrators only.');
      setTimeout(() => {
        this.router.navigate(['/dashboard']);
      }, 3000);
    }
  }

  /**
   * Load tournament and phases data.
   */
  private async loadTournamentData(): Promise<void> {
    this.isLoading.set(true);
    this.error.set(null);

    try {
      const id = this.route.snapshot.paramMap.get('tournamentId');
      if (!id) {
        throw new Error('Tournament ID is required');
      }

      this.tournamentId.set(id);

      // Load tournament details
      const tournamentData = await this.tournamentService.getTournamentById(id);
      this.tournament.set(tournamentData);

      // Adjust qualifier count default based on tournament type
      const isDoubles = tournamentData.tournamentType === 'DOUBLES';
      this.advanceForm.update(form => ({
        ...form,
        qualifierCount: isDoubles ? 2 : 4, // Doubles: 2 teams, Singles: 4 players
      }));

      // Load phases for current tournament only (much faster than loading all tournaments)
      await this.loadCurrentTournamentPhasesForDropdowns();

      // Load existing phase links and populate forms
      await this.loadExistingPhaseLinks();

      // Load phases with bracket info for the Overview tab
      await this.loadCurrentTournamentPhases();

      // Load categories for the Create Phase modal
      await this.loadTournamentCategories();

      this.isLoading.set(false);
    } catch (err: any) {
      console.error('Failed to load tournament data:', err);
      this.error.set(err.message || 'Failed to load tournament data');
      this.isLoading.set(false);
    }
  }

  /**
   * Load phases for CURRENT tournament only for dropdown selection.
   * This is much faster than loading all tournaments (which was causing 5+ second delays).
   * 
   * Phase linking almost always happens within the same tournament, so we optimize for that case.
   */
  private async loadCurrentTournamentPhasesForDropdowns(): Promise<void> {
    try {
      const currentTournamentId = this.tournamentId();
      if (!currentTournamentId) return;

      const tournament = this.tournament();
      if (!tournament) return;

      const phaseOptions: PhaseOption[] = [];

      // Fetch brackets for ONLY the current tournament
      const brackets = await this.bracketService.getBracketsByTournament(currentTournamentId);

      // For each bracket, fetch phases
      for (const bracket of brackets) {
        try {
          const phases = await this.phaseService.getPhasesByBracket(bracket.id);

          // Create options for each phase
          for (const phase of phases) {
            const phaseTypeLabel =
              phase.phaseType === 'QUALIFYING' ? 'Qualifying' :
              phase.phaseType === 'CONSOLATION' ? 'Consolation' :
              'Main Draw';
            const bracketName = bracket.category?.name || phaseTypeLabel;
            const categoryId = bracket.category?.id || (bracket as any).categoryId;

            phaseOptions.push({
              phaseId: phase.id,
              phaseName: phase.name,
              bracketId: bracket.id,
              bracketName,
              tournamentId: tournament.id,
              tournamentName: tournament.name,
              tournamentType: tournament.tournamentType,
              displayLabel: `${bracketName} > ${phase.name}`,
              categoryId,
            });
          }
        } catch (err) {
          console.warn(`Failed to load phases for bracket ${bracket.id}:`, err);
        }
      }

      this.allPhaseOptions.set(phaseOptions);
      this.sourcePhaseOptions.set(phaseOptions);
      this.targetPhaseOptions.set(phaseOptions);
    } catch (err: any) {
      console.error('Failed to load current tournament phase options:', err);
      // Don't throw - allow component to continue with empty options
    }
  }

  /**
   * Load existing phase links and populate form fields.
   */
  private async loadExistingPhaseLinks(): Promise<void> {
    try {
      const currentTournamentId = this.tournamentId();
      if (!currentTournamentId) return;

      // Get all brackets for current tournament
      const brackets = await this.bracketService.getBracketsByTournament(currentTournamentId);

      // Collect all phases from these brackets
      const allCurrentPhases: PhaseDto[] = [];
      for (const bracket of brackets) {
        try {
          const phases = await this.phaseService.getPhasesByBracket(bracket.id);
          allCurrentPhases.push(...phases);
        } catch (err) {
          console.warn(`Failed to load phases for bracket ${bracket.id}:`, err);
        }
      }

      // Check if any phase has a nextPhaseId set (existing link)
      const linkedPhase = allCurrentPhases.find(p => p.nextPhaseId);
      if (linkedPhase) {
        console.log('Found existing phase link:', linkedPhase);
        this.linkForm.set({
          sourcePhaseId: linkedPhase.id,
          targetPhaseId: linkedPhase.nextPhaseId!,
        });

        // Filter target phases based on source tournament type (without clearing target selection)
        this.filterTargetPhasesByType(linkedPhase.id);

        // Also populate advance form with the same link
        const targetOption = this.allPhaseOptions().find(opt => opt.phaseId === linkedPhase.nextPhaseId);
        if (targetOption) {
          this.advanceForm.update(form => ({
            ...form,
            sourcePhaseId: linkedPhase.id,
            targetPhaseId: linkedPhase.nextPhaseId!,
            categoryId: targetOption.categoryId || '',
          }));
        }
      }
    } catch (err: any) {
      console.error('Failed to load existing phase links:', err);
      // Don't throw - allow component to continue
    }
  }

  /**
   * Load phases with bracket info for the Overview tab.
   *
   * Fetches all brackets of the current tournament, then all phases per bracket,
   * and stores the flattened list with display-friendly info.
   */
  private async loadCurrentTournamentPhases(): Promise<void> {
    try {
      const currentTournamentId = this.tournamentId();
      if (!currentTournamentId) return;

      const brackets = await this.bracketService.getBracketsByTournament(currentTournamentId);
      const phaseInfos: PhaseInfo[] = [];

      for (const bracket of brackets) {
        try {
          const phases = await this.phaseService.getPhasesByBracket(bracket.id);
          const bracketName = bracket.category?.name || 'Main Draw';
          const categoryId = bracket.category?.id || (bracket as any).categoryId;

          for (const phase of phases) {
            phaseInfos.push({
              phaseId: phase.id,
              phaseName: phase.name,
              bracketId: bracket.id,
              bracketName,
              bracketType: bracket.bracketType ?? 'SINGLE_ELIMINATION',
              matchCount: phase.matchCount ?? 0,
              isCompleted: phase.isCompleted ?? false,
              phaseType: phase.phaseType ?? 'CUSTOM',
              isAutoGenerated: phase.isAutoGenerated ?? false,
              nextPhaseId: phase.nextPhaseId ?? null,
              sequenceOrder: phase.sequenceOrder ?? 0,
              categoryId,
            });
          }
        } catch (err) {
          console.warn(`Failed to load phases for bracket ${bracket.id}:`, err);
        }
      }

      // Sort by sequenceOrder
      phaseInfos.sort((a, b) => a.sequenceOrder - b.sequenceOrder);
      this.currentTournamentPhases.set(phaseInfos);
    } catch (err) {
      console.warn('Failed to load current tournament phases for overview:', err);
    }
  }

  /**
   * Load tournament categories for the Create Phase modal dropdown.
   */
  private async loadTournamentCategories(): Promise<void> {
    try {
      const id = this.tournamentId();
      if (!id) return;
      const categories = await this.categoryService.getCategoriesByTournament(id);
      this.tournamentCategories.set(categories);

      // Pre-select the first category if none is set
      if (categories.length > 0 && !this.createForm().categoryId) {
        this.createForm.update(f => ({...f, categoryId: categories[0].id}));
      }
    } catch (err) {
      console.warn('Failed to load tournament categories:', err);
    }
  }

  /**
   * Determines whether a flow-connector arrow should be rendered after phase at `index`.
   *
   * Rules (evaluated in order):
   * 1. Never draw a connector after the last phase.
   * 2. If the current phase has a `nextPhaseId` it belongs to a linked chain → draw connector.
   * 3. If the current phase has no `nextPhaseId` but the previous phase also had none,
   *    we are inside a consecutive unlinked group (e.g. consolation rounds not yet linked
   *    via the Link Phases tab) → draw connector so the group appears visually joined.
   * 4. Otherwise (current is null, previous was linked) the current phase is the terminal
   *    node of its group → no connector (creates the visual break between groups).
   *
   * @param index - Zero-based index of the phase in `currentTournamentPhases()`
   * @returns `true` when a connector should be drawn below this phase node
   */
  protected shouldShowConnector(index: number): boolean {
    const phases = this.currentTournamentPhases();
    if (index >= phases.length - 1) return false;
    const current = phases[index];
    const prev = index > 0 ? phases[index - 1] : null;
    if (current.nextPhaseId !== null && current.nextPhaseId !== undefined) return true;
    if (prev !== null && (prev.nextPhaseId === null || prev.nextPhaseId === undefined)) return true;
    return false;
  }

  /**
   * Update the phase name field in the create form.
   * Extracted from template to avoid unsupported arrow-function syntax in Angular event bindings.
   *
   * @param value - New phase name value
   */
  protected onCreateFormPhaseName(value: string): void {
    this.createForm.update(f => ({...f, phaseName: value}));
  }

  /**
   * Update the phase type field in the create form.
   *
   * @param value - New phase type value
   */
  protected onCreateFormPhaseType(value: string): void {
    this.createForm.update(f => ({
      ...f,
      phaseType: value as 'QUALIFYING' | 'MAIN' | 'CONSOLATION' | 'CUSTOM',
    }));
  }

  /**
   * Update the category ID field in the create form.
   *
   * @param value - New category ID value
   */
  protected onCreateFormCategoryId(value: string): void {
    this.createForm.update(f => ({...f, categoryId: value}));
  }

  /**
   * Update the bracket type field in the create form.
   *
   * @param value - New bracket type value
   */
  protected onCreateFormBracketType(value: string): void {
    this.createForm.update(f => ({
      ...f,
      bracketType: value as 'SINGLE_ELIMINATION' | 'ROUND_ROBIN' | 'MATCH_PLAY',
    }));
  }

  /**
   * Open the Create Phase modal.
   */
  protected openCreateModal(): void {
    // Reset form
    const firstCategoryId = this.tournamentCategories().length > 0 ? this.tournamentCategories()[0].id : '';
    this.createForm.set({
      phaseName: '',
      phaseType: 'CUSTOM',
      categoryId: firstCategoryId,
      bracketType: 'SINGLE_ELIMINATION',
    });
    this.showCreateModal.set(true);
  }

  /**
   * Close the Create Phase modal without saving.
   */
  protected closeCreateModal(): void {
    this.showCreateModal.set(false);
    this.clearMessages();
  }

  /**
   * Submit the Create Phase form and create a new phase.
   */
  protected async submitCreatePhase(): Promise<void> {
    const form = this.createForm();
    if (!form.phaseName.trim()) {
      this.error.set('Phase name is required.');
      return;
    }
    if (!form.categoryId) {
      this.error.set('Please select a category.');
      return;
    }

    this.isLoading.set(true);
    this.clearMessages();

    try {
      const result = await this.phaseService.createPhase({
        tournamentId: this.tournamentId()!,
        categoryId: form.categoryId,
        phaseName: form.phaseName.trim(),
        phaseType: form.phaseType,
        bracketType: form.bracketType,
      });

      this.success.set(result.message);
      this.showCreateModal.set(false);

      // Reload phase data to reflect the new phase
      await this.loadCurrentTournamentPhasesForDropdowns();
      await this.loadCurrentTournamentPhases();
    } catch (err: any) {
      this.error.set(err.message || 'Failed to create phase');
    } finally {
      this.isLoading.set(false);
    }
  }

  /**
   * Get the label for a bracket type.
   *
   * @param bracketType - Bracket type string
   * @returns Human-readable label
   */
  protected getBracketTypeLabel(bracketType: string): string {
    const labels: Record<string, string> = {
      SINGLE_ELIMINATION: 'Single Elimination',
      ROUND_ROBIN: 'Round Robin',
      MATCH_PLAY: 'Match Play',
    };
    return labels[bracketType] ?? bracketType;
  }

  /**
   * Find a phase's name from the allPhaseOptions signal using its ID.
   *
   * @param phaseId - Phase ID to look up
   * @returns Phase name or the raw ID if not found
   */
  protected getPhaseNameById(phaseId: string | null): string {
    if (!phaseId) return '';
    const option = this.allPhaseOptions().find(o => o.phaseId === phaseId);
    return option?.phaseName ?? phaseId;
  }

  /**
   * Switch between operation tabs.
   *
   * @param tab - Tab identifier
   */
  protected switchTab(tab: 'overview' | 'link' | 'advance' | 'consolation' | 'lucky-loser'): void {
    this.activeTab.set(tab);
    this.clearMessages();
  }

  /**
   * Check if a phase can be deleted (only manually created phases can be deleted).
   *
   * @param isAutoGenerated - Whether the phase was auto-generated by bracket generator
   * @returns True if the phase is deletable (not auto-generated)
   */
  protected canDeletePhase(isAutoGenerated: boolean | undefined): boolean {
    return !isAutoGenerated; // Can delete only if NOT auto-generated
  }

  /**
   * Delete a custom phase and its associated bracket.
   *
   * @param phaseId - ID of the phase to delete
   * @param phaseName - Name of the phase (for confirmation message)
   */
  protected async deletePhase(phaseId: string, phaseName: string): Promise<void> {
    const confirmed = window.confirm(
      `Are you sure you want to delete the phase "${phaseName}"?\n\nThis will also delete all associated matches. This action cannot be undone.`
    );

    if (!confirmed) {
      return;
    }

    this.isProcessing.set(true);
    this.clearMessages();

    try {
      const result = await this.phaseService.deletePhase(phaseId);
      this.success.set(result.message);

      // Reload phase data to reflect the deletion
      await this.loadCurrentTournamentPhasesForDropdowns();
      await this.loadCurrentTournamentPhases();
    } catch (err: any) {
      this.error.set(err.message || 'Failed to delete phase');
    } finally {
      this.isProcessing.set(false);
    }
  }

  /**
   * Get appropriate label for qualifier count based on tournament type.
   */
  protected getQualifierLabel(): string {
    const tournament = this.tournament();
    return tournament?.tournamentType === 'DOUBLES' ? 'Number of Team Qualifiers' : 'Number of Qualifiers';
  }

  /**
   * Get appropriate hint text for qualifier count based on tournament type.
   */
  protected getQualifierHint(): string {
    const tournament = this.tournament();
    return tournament?.tournamentType === 'DOUBLES' 
      ? 'How many top teams should advance (e.g., top 2)'
      : 'How many top participants should advance (e.g., top 4)';
  }

  /**
   * Get appropriate button text for qualifier advancement based on tournament type.
   */
  protected getQualifierButtonText(): string {
    const tournament = this.tournament();
    const count = this.advanceForm().qualifierCount;
    return tournament?.tournamentType === 'DOUBLES'
      ? `⬆️ Advance Top ${count} Teams`
      : `⬆️ Advance Top ${count} Qualifiers`;
  }

  /**
   * Filter target phase options when source phase changes.
   * Only shows phases from tournaments with matching tournament type (SINGLES/DOUBLES).
   *
   * @param phaseId - Selected source phase ID
   */
  protected onSourcePhaseChange(phaseId: string): void {
    // Clear target phase selection when source changes
    this.linkForm.update(form => ({
      ...form,
      sourcePhaseId: phaseId,
      targetPhaseId: '',
    }));

    // Filter target options based on tournament type
    this.filterTargetPhasesByType(phaseId);
  }

  /**
   * Filter target phase options based on source phase tournament type.
   * Separated from onSourcePhaseChange to allow reuse without clearing target selection.
   *
   * @param sourcePhaseId - Source phase ID to get tournament type from
   */
  private filterTargetPhasesByType(sourcePhaseId: string): void {
    if (!sourcePhaseId) {
      // No source selected - show all phases
      this.targetPhaseOptions.set(this.allPhaseOptions());
      return;
    }

    // Find the selected source phase to get its tournament type
    const sourcePhase = this.allPhaseOptions().find(p => p.phaseId === sourcePhaseId);
    if (!sourcePhase) {
      console.warn('Source phase not found:', sourcePhaseId);
      this.targetPhaseOptions.set(this.allPhaseOptions());
      return;
    }

    // Filter target phases to only show those from tournaments with matching type
    const compatiblePhases = this.allPhaseOptions().filter(
      p => p.tournamentType === sourcePhase.tournamentType
    );

    this.targetPhaseOptions.set(compatiblePhases);
    console.log(
      `Filtered target phases to ${compatiblePhases.length} ${sourcePhase.tournamentType} tournaments`
    );
  }

  /**
   * Auto-populate advance form when target phase changes.
   *
   * @param phaseId - Selected phase ID
   */
  protected onAdvanceTargetPhaseChange(phaseId: string): void {
    const selectedPhase = this.allPhaseOptions().find(p => p.phaseId === phaseId);
    this.advanceForm.update(form => ({
      ...form,
      targetPhaseId: phaseId,
      categoryId: selectedPhase?.categoryId || '',
    }));
  }

  /**
   * Auto-populate consolation form when main phase changes.
   *
   * @param phaseId - Selected phase ID
   */
  protected onConsolationMainPhaseChange(phaseId: string): void {
    const selectedPhase = this.allPhaseOptions().find(p => p.phaseId === phaseId);
    this.consolationForm.update(form => ({
      ...form,
      mainPhaseId: phaseId,
      categoryId: selectedPhase?.categoryId || '',
    }));
  }

  /**
   * Auto-populate lucky loser form when phase changes.
   * Also loads withdrawable participants for the selected phase/category.
   *
   * @param phaseId - Selected phase ID
   */
  protected async onLuckyLoserPhaseChange(phaseId: string): Promise<void> {
    const selectedPhase = this.allPhaseOptions().find(p => p.phaseId === phaseId);
    this.luckyLoserForm.update(form => ({
      ...form,
      phaseId: phaseId,
      categoryId: selectedPhase?.categoryId || '',
      withdrawnParticipantId: '', // Reset selection
    }));

    // Load accepted participants who can be withdrawn
    if (selectedPhase?.categoryId) {
      await this.loadWithdrawableParticipants(this.tournamentId()!, selectedPhase.categoryId);
    }
  }

  /**
   * Load ACCEPTED participants who can be withdrawn for Lucky Loser promotion.
   * For doubles tournaments, displays both players as "Player1 / Player2".
   * Deduplicates team pairs to show each team only once.
   *
   * @param tournamentId - Tournament ID
   * @param categoryId - Category ID
   */
  private async loadWithdrawableParticipants(tournamentId: string, categoryId: string): Promise<void> {
    try {
      const tournament = this.tournament();
      const isDoubles = tournament?.tournamentType === 'DOUBLES';

      // Fetch all registrations for this tournament
      const allRegistrations = await this.registrationService.getRegistrationsByTournament(tournamentId);

      // Filter to ACCEPTED registrations in this category (exclude WITHDRAWN and ALTERNATES)
      const acceptedRegs = allRegistrations.filter(r =>
        r.categoryId === categoryId &&
        r.status === 'ACCEPTED' &&
        (r.acceptanceType === 'DIRECT_ACCEPTANCE' || r.acceptanceType === 'QUALIFIER' || r.acceptanceType === 'LUCKY_LOSER')
      );

      const participantOptions: ParticipantOption[] = [];

      if (isDoubles) {
        // Track seen teams to avoid duplicates (both players have registrations)
        const seenTeams = new Set<string>();

        // For doubles: fetch both players for each registration
        for (const reg of acceptedRegs) {
          if (!reg.partnerId) continue; // Skip incomplete teams

          // Create a normalized team ID by sorting player IDs alphabetically
          // This ensures we only add each team once regardless of which player's registration we see first
          const teamKey = [reg.participantId, reg.partnerId].sort().join('|');
          if (seenTeams.has(teamKey)) continue; // Already processed this team
          seenTeams.add(teamKey);

          try {
            const player1 = await this.userRepository.findPublicById(reg.participantId);
            const player2 = await this.userRepository.findPublicById(reg.partnerId);

            if (player1 && player2) {
              const player1Name = player1.username || `${player1.firstName} ${player1.lastName}` || player1.email;
              const player2Name = player2.username || `${player2.firstName} ${player2.lastName}` || player2.email;
              const teamName = `${player1Name} / ${player2Name}`;
              const seedInfo = reg.seedNumber ? `Seed #${reg.seedNumber}` : reg.acceptanceType;

              participantOptions.push({
                participantId: reg.participantId, // Keep player1 ID for backend
                participantName: teamName,
                registrationId: reg.id,
                seedNumber: reg.seedNumber,
                acceptanceType: reg.acceptanceType,
                displayLabel: `${teamName} (${seedInfo})`,
              });
            }
          } catch (error) {
            console.warn(`Failed to load doubles team for registration ${reg.id}:`, error);
          }
        }
      } else {
        // For singles: fetch individual users
        for (const reg of acceptedRegs) {
          try {
            const user = await this.userRepository.findPublicById(reg.participantId);
            if (user) {
              const displayName = user.username || `${user.firstName} ${user.lastName}` || user.email;
              const seedInfo = reg.seedNumber ? `Seed #${reg.seedNumber}` : reg.acceptanceType;

              participantOptions.push({
                participantId: reg.participantId,
                participantName: displayName,
                registrationId: reg.id,
                seedNumber: reg.seedNumber,
                acceptanceType: reg.acceptanceType,
                displayLabel: `${displayName} (${seedInfo})`,
              });
            }
          } catch (error) {
            console.warn(`Failed to load user ${reg.participantId}:`, error);
          }
        }
      }

      // Sort by seed number (seeded players first), then by name
      participantOptions.sort((a, b) => {
        if (a.seedNumber && b.seedNumber) return a.seedNumber - b.seedNumber;
        if (a.seedNumber) return -1;
        if (b.seedNumber) return 1;
        return a.participantName.localeCompare(b.participantName);
      });

      this.withdrawableParticipants.set(participantOptions);
      console.log(`Loaded ${participantOptions.length} withdrawable ${isDoubles ? 'teams' : 'participants'}`);
    } catch (error) {
      console.error('Failed to load withdrawable participants:', error);
      this.withdrawableParticipants.set([]);
    }
  }

  /**
   * Link two phases in sequence.
   */
  protected async linkPhases(): Promise<void> {
    this.isProcessing.set(true);
    this.clearMessages();

    try {
      const formData = this.linkForm();

      if (!formData.sourcePhaseId || !formData.targetPhaseId) {
        throw new Error('Both source and target phases are required');
      }

      const result = await this.phaseService.linkPhases({
        sourcePhaseId: formData.sourcePhaseId,
        targetPhaseId: formData.targetPhaseId,
      });

      this.success.set(result.message);
      // Don't reset form - keep selections visible
      await this.loadTournamentData();
    } catch (err: any) {
      this.error.set(err.message || 'Failed to link phases');
    } finally {
      this.isProcessing.set(false);
    }
  }

  /**
   * Advance top qualifiers from Round Robin to next phase.
   */
  protected async advanceQualifiers(): Promise<void> {
    this.isProcessing.set(true);
    this.clearMessages();

    try {
      const formData = this.advanceForm();
      const targetPhaseOption = this.allPhaseOptions().find(option => option.phaseId === formData.targetPhaseId);
      const targetTournamentId = targetPhaseOption?.tournamentId || '';

      if (!formData.sourcePhaseId || !formData.targetPhaseId) {
        throw new Error('Source phase and target phase are required');
      }

      if (!formData.categoryId) {
        throw new Error('Category ID is required');
      }

      if (!targetTournamentId) {
        throw new Error('Could not resolve target tournament from selected phase');
      }

      if (formData.qualifierCount < 1) {
        throw new Error('Qualifier count must be at least 1');
      }

      const result = await this.phaseService.advanceQualifiers({
        sourcePhaseId: formData.sourcePhaseId,
        targetPhaseId: formData.targetPhaseId,
        qualifierCount: formData.qualifierCount,
        tournamentId: targetTournamentId,
        categoryId: formData.categoryId,
      });

      this.success.set(`${result.message}. Qualified: ${result.qualifiedParticipants.length} participants.`);
      // Don't reset form - keep selections visible
      await this.loadTournamentData();
    } catch (err: any) {
      this.error.set(err.message || 'Failed to advance qualifiers');
    } finally {
      this.isProcessing.set(false);
    }
  }

  /**
   * Create consolation draw for eliminated participants.
   */
  protected async createConsolationDraw(): Promise<void> {
    this.isProcessing.set(true);
    this.clearMessages();

    try {
      const formData = this.consolationForm();
      const tournamentId = this.tournamentId();

      if (!formData.mainPhaseId || !tournamentId) {
        throw new Error('Main phase and tournament ID are required');
      }

      if (!formData.categoryId) {
        throw new Error('Category ID is required');
      }

      const result = await this.phaseService.createConsolationDraw({
        mainPhaseId: formData.mainPhaseId,
        tournamentId,
        categoryId: formData.categoryId,
        eliminationRound: formData.eliminationRound || undefined,
      });

      // Store consolation phase ID for population
      this.consolationForm.update(form => ({
        ...form,
        consolationPhaseId: result.consolationPhase.id,
      }));

      this.success.set(`${result.message}. Now populate it with losers from the main phase.`);
      await this.loadTournamentData();
    } catch (err: any) {
      this.error.set(err.message || 'Failed to create consolation draw');
    } finally {
      this.isProcessing.set(false);
    }
  }

  /**
   * Populate consolation draw with losers from completed main phase matches.
   */
  protected async populateConsolationDraw(): Promise<void> {
    this.isProcessing.set(true);
    this.clearMessages();

    try {
      const formData = this.consolationForm();
      const tournamentId = this.tournamentId();

      if (!formData.consolationPhaseId || !tournamentId || !formData.categoryId) {
        throw new Error('Consolation phase ID, tournament ID, and category ID are required');
      }

      const result = await this.phaseService.populateConsolationDraw({
        consolationPhaseId: formData.consolationPhaseId,
        tournamentId,
        categoryId: formData.categoryId,
      });

      this.success.set(`${result.message}. ${result.losersCount} losers added, ${result.matchesCreated} matches created. Refresh bracket to see consolation matches.`);
      this.resetConsolationForm();
      await this.loadTournamentData();
    } catch (err: any) {
      this.error.set(err.message || 'Failed to populate consolation draw');
    } finally {
      this.isProcessing.set(false);
    }
  }

  /**
   * Promote alternate to Lucky Loser when participant withdraws.
   */
  protected async promoteLuckyLoser(): Promise<void> {
    this.isProcessing.set(true);
    this.clearMessages();

    try {
      const formData = this.luckyLoserForm();
      const tournamentId = this.tournamentId();

      if (!formData.withdrawnParticipantId || !formData.phaseId || !tournamentId) {
        throw new Error('Withdrawn participant, phase, and tournament ID are required');
      }

      if (!formData.categoryId) {
        throw new Error('Category ID is required');
      }

      const result = await this.phaseService.promoteLuckyLoser({
        withdrawnParticipantId: formData.withdrawnParticipantId,
        phaseId: formData.phaseId,
        tournamentId,
        categoryId: formData.categoryId,
      });

      if (result.promotedParticipantId) {
        this.success.set(`${result.message}. Promoted participant: ${result.promotedParticipantId}. Refresh the tournament details page to see updated participant list.`);
      } else {
        this.success.set(`${result.message}. Refresh the tournament details page to see updated participant list.`);
      }

      // Reload withdrawable participants to reflect the withdrawn player being removed
      if (formData.phaseId && formData.categoryId) {
        await this.loadWithdrawableParticipants(tournamentId, formData.categoryId);
      }

      // Clear only the withdrawn player selection, keep phase selected
      this.luckyLoserForm.update(form => ({
        ...form,
        withdrawnParticipantId: '',
      }));

      await this.loadTournamentData();
    } catch (err: any) {
      this.error.set(err.message || 'Failed to promote Lucky Loser');
    } finally {
      this.isProcessing.set(false);
    }
  }

  /**
   * Clear success and error messages.
   */
  private clearMessages(): void {
    this.error.set(null);
    this.success.set(null);
  }

  /**
   * Reset link form.
   */
  private resetLinkForm(): void {
    this.linkForm.set({
      sourcePhaseId: '',
      targetPhaseId: '',
    });
  }

  /**
   * Reset advance form.
   */
  private resetAdvanceForm(): void {
    this.advanceForm.update((form) => ({
      ...form,
      sourcePhaseId: '',
      targetPhaseId: '',
      qualifierCount: 4,
    }));
  }

  /**
   * Reset consolation form.
   */
  private resetConsolationForm(): void {
    this.consolationForm.update((form) => ({
      ...form,
      mainPhaseId: '',
      eliminationRound: 1,
      consolationPhaseId: '',
    }));
  }

  /**
   * Reset lucky loser form.
   */
  private resetLuckyLoserForm(): void {
    this.luckyLoserForm.set({
      withdrawnParticipantId: '',
      phaseId: '',
      categoryId: '',
    });
  }

  /**
   * Format date for display.
   *
   * @param date - Date to format
   * @returns Formatted date string
   */
  protected formatDate(date: string | Date): string {
    const dateObj = typeof date === 'string' ? new Date(date) : date;
    return dateObj.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  }
}
