/**
 * University of La Laguna
 * School of Engineering and Technology
 * Degree in Computer Engineering
 * Final Degree Project (TFG)
 *
 * @author Fabián González Lence <alu0101549491@ull.edu.es>
 * @since April 20, 2026
 * @file e2e/helpers/seed.helper.ts
 * @desc API-driven seed helper for creating and cleaning E2E data when backend endpoints are available.
 * @see {@link https://github.com/alu0101549491/TFG-Fabian-Gonzalez-Lence/tree/main/projects/5-TennisTournamentManager}
 * @see {@link https://typescripttutorial.net}
 */

import {ApiHelper, type AuthSession} from './api.helper';

/** Minimal seed identifiers tracked for teardown. */
export interface SeededTournament {
  id: string;
  name: string;
  categoryId?: string;
  courtId?: string;
  bracketId?: string;
  matchId?: string;
  registrationIds?: string[];
  participantIds?: string[];
}

/** Partial tournament creation options used to tailor API-seeded fixtures. */
export interface TournamentSeedOptions {
  description?: string;
  startDate?: string;
  endDate?: string;
  registrationOpenDate?: string;
  registrationCloseDate?: string;
  location?: string;
  surface?: string;
  facilityType?: string;
  tournamentType?: string;
  maxParticipants?: number;
  registrationFee?: number;
  currency?: string;
  rankingSystem?: string;
  regulations?: string;
  primaryColor?: string;
  secondaryColor?: string;
  logoUrl?: string;
}

/** Supported match seed states used by critical E2E fixtures. */
export interface SinglesMatchSeedOptions {
  categoryName?: string;
  tournamentStatuses?: string[];
  courtName?: string;
  scheduledTime?: string;
  matchStatus?: string;
  ballProvider?: string;
  startTime?: string;
  publishBracket?: boolean;
  tournamentOptions?: TournamentSeedOptions;
}

/** Options used to seed a singles match with a participant-submitted pending result. */
export interface PendingResultSeedOptions extends SinglesMatchSeedOptions {
  submitterToken: string;
  winnerId: string;
  setScores: string[];
  playerComments?: string;
}

/**
 * Helper focused on API seeding instead of slow UI bootstrapping.
 */
export class SeedHelper {
  private readonly apiHelper: ApiHelper;
  private readonly adminSession: AuthSession;
  private readonly createdTournamentIds: string[] = [];
  private readonly createdUserIds: string[] = [];

  public constructor(apiHelper: ApiHelper, adminSession: AuthSession) {
    this.apiHelper = apiHelper;
    this.adminSession = adminSession;
  }

  /**
   * Registers a transient player account for isolated tests.
   *
   * @param suffix - Unique suffix used in email/username generation
   * @returns Authenticated session for the new player
   */
  public async createPlayer(suffix: string): Promise<AuthSession> {
    const session = await this.apiHelper.post<AuthSession>('/auth/register', {
      email: `${suffix}@e2e-tennis.test`,
      password: 'Password123!',
      firstName: 'E2E',
      lastName: suffix,
      username: `e2e_${suffix}`,
      phone: null,
    }, undefined, 201);

    this.createdUserIds.push(session.user.id);
    return session;
  }

  /**
   * Creates a tournament skeleton suitable for create/edit/order-of-play tests.
   *
   * @param name - Tournament name
   * @returns Seed summary for the created tournament
   */
  public async createTournament(name: string, options: TournamentSeedOptions = {}): Promise<SeededTournament> {
    const tournament = await this.apiHelper.post<{id: string}>('/tournaments', {
      name,
      description: options.description ?? `${name} generated by Playwright`,
      startDate: options.startDate ?? '2026-06-01T09:00:00.000Z',
      endDate: options.endDate ?? '2026-06-03T18:00:00.000Z',
      registrationOpenDate: options.registrationOpenDate ?? '2026-05-20T09:00:00.000Z',
      registrationCloseDate: options.registrationCloseDate ?? '2026-05-31T18:00:00.000Z',
      location: options.location ?? 'La Laguna',
      surface: options.surface ?? 'CLAY',
      facilityType: options.facilityType ?? 'OUTDOOR',
      tournamentType: options.tournamentType ?? 'SINGLES',
      maxParticipants: options.maxParticipants ?? 16,
      registrationFee: options.registrationFee ?? 0,
      currency: options.currency ?? 'EUR',
      rankingSystem: options.rankingSystem ?? 'POINTS_BASED',
      regulations: options.regulations ?? 'Automated E2E tournament regulations.',
      primaryColor: options.primaryColor ?? '#2563eb',
      secondaryColor: options.secondaryColor ?? '#10b981',
      logoUrl: options.logoUrl ?? null,
    }, this.adminSession.token, 201);

    this.createdTournamentIds.push(tournament.id);
    return {id: tournament.id, name};
  }

  /**
   * Transitions a tournament through one or more statuses.
   *
   * @param tournamentId - Tournament identifier
   * @param statuses - Ordered statuses to apply
   */
  public async updateTournamentStatus(tournamentId: string, statuses: string | string[]): Promise<void> {
    const orderedStatuses = Array.isArray(statuses) ? statuses : [statuses];

    for (const status of orderedStatuses) {
      await this.apiHelper.put(`/tournaments/${tournamentId}/status`, {status}, this.adminSession.token, 200);
    }
  }

  /**
   * Creates a category for an existing tournament.
   *
   * @param tournamentId - Tournament identifier
   * @param name - Category name
   * @returns Category identifier
   */
  public async createCategory(tournamentId: string, name: string): Promise<string> {
    const category = await this.apiHelper.post<{id: string}>('/categories', {
      tournamentId,
      name,
      gender: 'MIXED',
      ageGroup: 'OPEN',
      maxParticipants: 16,
      description: `${name} category`,
    }, this.adminSession.token, 201);
    return category.id;
  }

  /**
   * Creates a category with a custom participant cap.
   *
   * @param tournamentId - Tournament identifier
   * @param name - Category name
   * @param maxParticipants - Maximum participants allowed in the category
   * @returns Category identifier
   */
  public async createSizedCategory(
    tournamentId: string,
    name: string,
    maxParticipants: number,
  ): Promise<string> {
    const category = await this.apiHelper.post<{id: string}>('/categories', {
      tournamentId,
      name,
      gender: 'MIXED',
      ageGroup: 'OPEN',
      maxParticipants,
      description: `${name} category`,
    }, this.adminSession.token, 201);
    return category.id;
  }

  /**
   * Creates a court for order-of-play and match scheduling tests.
   *
   * @param tournamentId - Tournament identifier
   * @param name - Court name
   * @returns Court identifier
   */
  public async createCourt(tournamentId: string, name: string): Promise<string> {
    const court = await this.apiHelper.post<{id: string}>('/courts', {
      tournamentId,
      name,
      surface: 'HARD',
      openingTime: '09:00',
      closingTime: '21:00',
      isAvailable: true,
    }, this.adminSession.token, 201);
    return court.id;
  }

  /**
   * Registers a participant into a category through the admin enrollment path.
   *
   * @param categoryId - Category identifier
   * @param participantId - Participant identifier
   * @returns Registration identifier
   */
  public async registerParticipant(categoryId: string, participantId: string): Promise<string> {
    const registration = await this.apiHelper.post<{id: string}>('/registrations', {
      categoryId,
      participantId,
    }, this.adminSession.token, 201);

    return registration.id;
  }

  /**
   * Approves a registration so it becomes bracket-eligible.
   *
   * @param registrationId - Registration identifier
   * @param acceptanceType - Accepted draw-slot type
   */
  public async approveRegistration(
    registrationId: string,
    acceptanceType: string = 'DIRECT_ACCEPTANCE',
  ): Promise<void> {
    await this.apiHelper.put(
      `/registrations/${registrationId}/status`,
      {
        status: 'ACCEPTED',
        acceptanceType,
      },
      this.adminSession.token,
      200,
    );
  }

  /**
   * Generates a bracket for a category and returns its identifier.
   *
   * @param tournamentId - Tournament identifier
   * @param categoryId - Category identifier
   * @param participantCount - Number of accepted participants
   * @returns Bracket identifier
   */
  public async createBracket(
    tournamentId: string,
    categoryId: string,
    participantCount: number,
    bracketType: string = 'SINGLE_ELIMINATION',
  ): Promise<string> {
    const normalizedParticipantCount = Math.max(participantCount, 2);
    const size = bracketType === 'ROUND_ROBIN'
      ? normalizedParticipantCount
      : Math.pow(2, Math.ceil(Math.log2(normalizedParticipantCount)));
    const totalRounds = bracketType === 'ROUND_ROBIN'
      ? Math.max(normalizedParticipantCount - 1, 1)
      : Math.log2(size);

    const bracket = await this.apiHelper.post<{id: string}>('/brackets', {
      tournamentId,
      categoryId,
      bracketType,
      size,
      totalRounds,
      structure: null,
      isPublished: false,
    }, this.adminSession.token, 201);

    return bracket.id;
  }

  /**
   * Publishes a draft bracket.
   *
   * @param bracketId - Bracket identifier
   */
  public async publishBracket(bracketId: string): Promise<void> {
    await this.apiHelper.put(
      `/brackets/${bracketId}`,
      {isPublished: true},
      this.adminSession.token,
      200,
    );
  }

  /**
   * Retrieves all matches for a bracket.
   *
   * @param bracketId - Bracket identifier
   * @returns Bracket matches
   */
  public async getMatchesByBracket(bracketId: string): Promise<Array<Record<string, unknown>>> {
    return this.apiHelper.get<Array<Record<string, unknown>>>(
      `/matches?bracketId=${bracketId}`,
      this.adminSession.token,
    );
  }

  /**
   * Updates a match directly through the admin API.
   *
   * @param matchId - Match identifier
   * @param data - Partial match payload
   */
  public async updateMatch(matchId: string, data: Record<string, unknown>): Promise<void> {
    await this.apiHelper.put(`/matches/${matchId}`, data, this.adminSession.token, 200);
  }

  /**
   * Creates a deterministic singles bracket fixture with one playable match.
   *
   * @param name - Tournament name
   * @param participantIds - Participants to register and approve
   * @param options - Optional match and tournament shaping options
   * @returns Seed summary with tournament, bracket, court, and match identifiers
   */
  public async createSinglesMatchFixture(
    name: string,
    participantIds: string[],
    options: SinglesMatchSeedOptions = {},
  ): Promise<SeededTournament> {
    if (participantIds.length < 2) {
      throw new Error('At least two participant IDs are required to seed a singles match fixture');
    }

    const tournament = await this.createTournament(name, {
      maxParticipants: Math.max(options.tournamentOptions?.maxParticipants ?? 16, participantIds.length),
      ...options.tournamentOptions,
    });
    const categoryId = await this.createSizedCategory(
      tournament.id,
      options.categoryName ?? 'Mixed Open Singles',
      Math.max(16, participantIds.length),
    );

    if (options.tournamentStatuses && options.tournamentStatuses.length > 0) {
      await this.updateTournamentStatus(tournament.id, options.tournamentStatuses);
    }

    const registrationIds: string[] = [];
    for (const participantId of participantIds) {
      const registrationId = await this.registerParticipant(categoryId, participantId);
      registrationIds.push(registrationId);
      await this.approveRegistration(registrationId);
    }

    const bracketId = await this.createBracket(tournament.id, categoryId, participantIds.length);
    if (options.publishBracket) {
      await this.publishBracket(bracketId);
    }

    const matches = await this.getMatchesByBracket(bracketId);
    const seededMatch = matches.find((match) => match.participant1Id && match.participant2Id) ?? matches[0];
    if (!seededMatch || typeof seededMatch.id !== 'string') {
      throw new Error(`No playable match was generated for seeded tournament ${name}`);
    }

    let courtId: string | undefined;
    const shouldPrepareCourt = Boolean(
      options.courtName
      || options.scheduledTime
      || options.matchStatus
      || options.ballProvider
      || options.startTime,
    );

    if (shouldPrepareCourt) {
      courtId = await this.createCourt(tournament.id, options.courtName ?? 'E2E Court 1');

      const matchPayload: Record<string, unknown> = {
        courtId,
      };

      if (options.scheduledTime) {
        matchPayload.scheduledTime = options.scheduledTime;
      }
      if (options.matchStatus) {
        matchPayload.status = options.matchStatus;
      }
      if (options.ballProvider) {
        matchPayload.ballProvider = options.ballProvider;
      }
      if (options.startTime) {
        matchPayload.startTime = options.startTime;
      }

      await this.updateMatch(seededMatch.id, matchPayload);
    }

    return {
      ...tournament,
      categoryId,
      courtId,
      bracketId,
      matchId: seededMatch.id,
      registrationIds,
      participantIds,
    };
  }

  /**
   * Creates a scheduled singles fixture and submits a result as one participant.
   *
   * @param name - Tournament name
   * @param participantIds - Participants to register and approve
   * @param options - Result-submission options for the seeded pending state
   * @returns Seed summary enriched with the created pending result identifier
   */
  public async createPendingResultFixture(
    name: string,
    participantIds: string[],
    options: PendingResultSeedOptions,
  ): Promise<SeededTournament & {pendingResultId: string}> {
    const fixture = await this.createSinglesMatchFixture(name, participantIds, {
      ...options,
      scheduledTime: options.scheduledTime ?? '2026-06-12T10:30:00.000Z',
      matchStatus: options.matchStatus ?? 'SCHEDULED',
    });

    if (!fixture.matchId) {
      throw new Error(`Pending-result fixture ${name} did not generate a match identifier`);
    }

    const result = await this.apiHelper.post<{id: string}>(
      `/matches/${fixture.matchId}/result`,
      {
        winnerId: options.winnerId,
        setScores: options.setScores,
        player1Games: 0,
        player2Games: 0,
        playerComments: options.playerComments,
      },
      options.submitterToken,
      201,
    );

    return {
      ...fixture,
      pendingResultId: result.id,
    };
  }

  /**
   * Deletes all resources created through this helper.
   */
  public async cleanAll(): Promise<void> {
    for (const tournamentId of [...this.createdTournamentIds].reverse()) {
      try {
        await this.apiHelper.delete(`/tournaments/${tournamentId}`, this.adminSession.token, true);
      } catch (error) {
        console.warn(`Seed cleanup skipped tournament ${tournamentId}:`, error);
      }
    }

    if (this.adminSession.user.role !== 'SYSTEM_ADMIN') {
      return;
    }

    for (const userId of [...this.createdUserIds].reverse()) {
      try {
        await this.apiHelper.delete(`/users/${userId}`, this.adminSession.token, true);
      } catch (error) {
        console.warn(`Seed cleanup skipped user ${userId}:`, error);
      }
    }
  }
}