-- Step 1: Add all new enum values to the existing enum
ALTER TYPE "ProjectType" ADD VALUE IF NOT EXISTS 'TOPOGRAPHY';
ALTER TYPE "ProjectType" ADD VALUE IF NOT EXISTS 'CADASTRE';
ALTER TYPE "ProjectType" ADD VALUE IF NOT EXISTS 'GIS';
ALTER TYPE "ProjectType" ADD VALUE IF NOT EXISTS 'HYDROLOGY';
ALTER TYPE "ProjectType" ADD VALUE IF NOT EXISTS 'CIVIL_ENGINEERING';
ALTER TYPE "ProjectType" ADD VALUE IF NOT EXISTS 'ENVIRONMENTAL_DOCUMENT';
ALTER TYPE "ProjectType" ADD VALUE IF NOT EXISTS 'ALTERNATIVES_STUDY';
ALTER TYPE "ProjectType" ADD VALUE IF NOT EXISTS 'GEOLOGICAL_STUDY';
ALTER TYPE "ProjectType" ADD VALUE IF NOT EXISTS 'HYDROGEOLOGICAL_STUDY';
ALTER TYPE "ProjectType" ADD VALUE IF NOT EXISTS 'RISK_STUDY';
ALTER TYPE "ProjectType" ADD VALUE IF NOT EXISTS 'CONSTRUCTION_MANAGEMENT';
ALTER TYPE "ProjectType" ADD VALUE IF NOT EXISTS 'MISCELLANEOUS';

-- Step 2: Update existing data from old values to new values
UPDATE projects SET type = 'MISCELLANEOUS' 
WHERE type IN ('RESIDENTIAL', 'COMMERCIAL', 'INDUSTRIAL', 'PUBLIC');

-- Step 3: Now we need to recreate the enum without the old values
-- This is complex in PostgreSQL, so we'll use a workaround:
-- Create a new enum, alter the column, drop the old enum

CREATE TYPE "ProjectType_new" AS ENUM (
  'TOPOGRAPHY',
  'CADASTRE',
  'GIS',
  'HYDROLOGY',
  'CIVIL_ENGINEERING',
  'ENVIRONMENTAL_DOCUMENT',
  'ALTERNATIVES_STUDY',
  'GEOLOGICAL_STUDY',
  'HYDROGEOLOGICAL_STUDY',
  'RISK_STUDY',
  'CONSTRUCTION_MANAGEMENT',
  'MISCELLANEOUS'
);

ALTER TABLE projects ALTER COLUMN type TYPE "ProjectType_new" USING (type::text::"ProjectType_new");
DROP TYPE "ProjectType";
ALTER TYPE "ProjectType_new" RENAME TO "ProjectType";
