-- Create all tables from TypeORM entities (24 tables)
-- TODO: Convert each TypeORM entity to SQL CREATE TABLE

-- Core tables: users, tournaments, categories, phases, brackets, matches, scores
-- Registration: registrations, doubles_teams, partner_invitations
-- Scheduling: order_of_play, courts
-- Stats: standings, statistics, global_rankings, match_results
-- Communication: announcements, notifications, notification_preferences, push_subscriptions
-- Admin: payments, sanctions, audit_logs

-- Example:
-- CREATE TABLE tournaments (
--   id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
--   name TEXT NOT NULL,
--   start_date DATE NOT NULL,
--   end_date DATE NOT NULL,
--   status tournament_status NOT NULL DEFAULT 'draft',
--   surface tournament_surface,
--   max_participants INTEGER,
--   organizer_id UUID REFERENCES auth.users(id),
--   created_at TIMESTAMPTZ DEFAULT NOW(),
--   updated_at TIMESTAMPTZ DEFAULT NOW()
-- );
