/**
 * University of La Laguna
 * School of Engineering and Technology
 * Degree in Computer Engineering
 * Final Degree Project (TFG)
 *
 * @author Fabián González Lence <alu0101549491@ull.edu.es>
 * @since March 8, 2026
 * @file backend/src/infrastructure/repositories/interfaces/file.repository.interface.ts
 * @desc File repository interface for Prisma-based data access
 * @see {@link https://github.com/alu0101549491/TFG-Fabian-Gonzalez-Lence/tree/main/projects/4-CartographicProjectManager}
 * @see {@link https://typescripttutorial.net}
 */

import type {File, FileType} from '@prisma/client';

/**
 * File repository interface
 */
export interface IFileRepository {
  /**
   * Find a file by its id.
   *
   * @param id - File id
   */
  findById(id: string): Promise<File | null>;

  /**
   * List all files for a project.
   *
   * @param projectId - Project id
   */
  findByProjectId(projectId: string): Promise<File[]>;

  /**
   * List all files uploaded by a user.
   *
   * @param uploaderId - Uploader user id
   */
  findByUploaderId(uploaderId: string): Promise<File[]>;

  /**
   * List all files by type.
   *
   * @param type - File type
   */
  findByType(type: FileType): Promise<File[]>;

  /**
   * Create a file record.
   *
   * @param data - File fields (id/uploadedAt are generated by persistence)
   */
  create(data: Omit<File, 'id' | 'uploadedAt'>): Promise<File>;

  /**
   * Update a file record.
   *
   * @param id - File id
   * @param data - Partial file fields
   */
  update(id: string, data: Partial<File>): Promise<File>;

  /**
   * Delete a file record.
   *
   * @param id - File id
   */
  delete(id: string): Promise<void>;
}
