/**
 * University of La Laguna
 * School of Engineering and Technology
 * Degree in Computer Engineering
 * Final Degree Project (TFG)
 *
 * @author Fabián González Lence <alu0101549491@ull.edu.es>
 * @since March 8, 2026
 * @file backend/src/infrastructure/repositories/interfaces/message.repository.interface.ts
 * @desc Message repository interface for Prisma-based data access
 * @see {@link https://github.com/alu0101549491/TFG-Fabian-Gonzalez-Lence/tree/main/projects/4-CartographicProjectManager}
 * @see {@link https://typescripttutorial.net}
 */

import type {Message} from '@prisma/client';

/**
 * Message repository interface
 */
export interface IMessageRepository {
  /**
   * Find a message by id.
   *
   * @param id - Message id
   */
  findById(id: string): Promise<Message | null>;

  /**
   * Count messages for a project.
   *
   * @param projectId - Project id
   */
  countByProjectId(projectId: string): Promise<number>;

  /**
   * List all messages for a project.
   *
   * @param projectId - Project id
   */
  findByProjectId(projectId: string): Promise<Message[]>;

  /**
   * List messages for a project with pagination.
   *
   * @param projectId - Project id
   * @param limit - Page size
   * @param offset - Offset from start
   */
  findByProjectIdPaginated(projectId: string, limit: number, offset: number): Promise<Message[]>;

  /**
   * List messages sent by a specific user.
   *
   * @param senderId - Sender user id
   */
  findBySenderId(senderId: string): Promise<Message[]>;

  /**
   * Create a message.
   *
   * @param data - Message fields (id/sentAt are generated by persistence)
   */
  create(data: Omit<Message, 'id' | 'sentAt'>): Promise<Message>;

  /**
   * Delete a message by id.
   *
   * @param id - Message id
   */
  delete(id: string): Promise<void>;

  /**
   * Count unread messages for a given project and user.
   *
   * @param projectId - Project id
   * @param userId - User id
   */
  countUnreadByProjectAndUser(projectId: string, userId: string): Promise<number>;

  /**
   * Mark all messages in a project as read for a user.
   *
   * @param projectId - Project id
   * @param userId - User id
   */
  markAllAsRead(projectId: string, userId: string): Promise<void>;
}
