/**
 * University of La Laguna
 * School of Engineering and Technology
 * Degree in Computer Engineering
 * Final Degree Project (TFG)
 *
 * @author Fabián González Lence <alu0101549491@ull.edu.es>
 * @since March 8, 2026
 * @file backend/src/infrastructure/repositories/interfaces/notification.repository.interface.ts
 * @desc Notification repository interface for Prisma-based data access
 * @see {@link https://github.com/alu0101549491/TFG-Fabian-Gonzalez-Lence/tree/main/projects/4-CartographicProjectManager}
 * @see {@link https://typescripttutorial.net}
 */

import type {Notification} from '@prisma/client';

/**
 * Notification repository interface
 */
export interface INotificationRepository {
  /**
   * Find a notification by id.
   *
   * @param id - Notification id
   */
  findById(id: string): Promise<Notification | null>;

  /**
   * List all notifications for a user.
   *
   * @param userId - User id
   */
  findByUserId(userId: string): Promise<Notification[]>;

  /**
   * List unread notifications for a user.
   *
   * @param userId - User id
   */
  findUnreadByUserId(userId: string): Promise<Notification[]>;

  /**
   * Create a new notification.
   *
   * @param data - Notification fields (id/timestamps/read-state are generated by persistence)
   */
  create(data: Omit<Notification, 'id' | 'createdAt' | 'readAt' | 'isRead'>): Promise<Notification>;

  /**
   * Mark a notification as read.
   *
   * @param id - Notification id
   */
  markAsRead(id: string): Promise<Notification>;

  /**
   * Delete a notification by id.
   *
   * @param id - Notification id
   */
  delete(id: string): Promise<void>;

  /**
   * Delete all notifications for a user.
   *
   * @param userId - User id
   */
  deleteAllForUser(userId: string): Promise<void>;
}
