/**
 * University of La Laguna
 * School of Engineering and Technology
 * Degree in Computer Engineering
 * Final Degree Project (TFG)
 *
 * @author Fabián González Lence <alu0101549491@ull.edu.es>
 * @since March 8, 2026
 * @file backend/src/infrastructure/repositories/interfaces/task.repository.interface.ts
 * @desc Task repository interface for Prisma-based data access
 * @see {@link https://github.com/alu0101549491/TFG-Fabian-Gonzalez-Lence/tree/main/projects/4-CartographicProjectManager}
 * @see {@link https://typescripttutorial.net}
 */

import type {Prisma, Task, TaskStatus} from '@prisma/client';

export type TaskWithDetails = Prisma.TaskGetPayload<{
  include: {
    project: true;
    creator: true;
    assignee: true;
    files: {include: {file: true}};
  };
}>;

export type TaskWithUsers = Prisma.TaskGetPayload<{
  include: {
    project: true;
    creator: true;
    assignee: true;
  };
}>;

/**
 * Task repository interface
 */
export interface ITaskRepository {
  /**
   * Find a task by its id.
   *
   * @param id - Task id
   * @returns Task with related entities, or null when not found
   */
  findById(id: string): Promise<TaskWithDetails | null>;

  /**
   * List all tasks.
   *
   * @returns Tasks with related user/project info
   */
  findAll(): Promise<TaskWithUsers[]>;

  /**
   * List all tasks for a project.
   *
   * @param projectId - Project id
   */
  findByProjectId(projectId: string): Promise<TaskWithUsers[]>;

  /**
   * List all tasks assigned to a user.
   *
   * @param assigneeId - Assignee user id
   */
  findByAssigneeId(assigneeId: string): Promise<TaskWithUsers[]>;

  /**
   * List all tasks created by a user.
   *
   * @param creatorId - Creator user id
   */
  findByCreatorId(creatorId: string): Promise<TaskWithUsers[]>;

  /**
   * List all tasks by status.
   *
   * @param status - Task status
   */
  findByStatus(status: TaskStatus): Promise<TaskWithUsers[]>;

  /**
   * Create a new task.
   *
   * @param data - Task fields (id/timestamps are generated by persistence)
   */
  create(
    data: Omit<Task, 'id' | 'createdAt' | 'updatedAt' | 'completedAt' | 'confirmedAt'>,
  ): Promise<TaskWithUsers>;

  /**
   * Update a task by id.
   *
   * @param id - Task id
   * @param data - Partial task fields
   */
  update(id: string, data: Partial<Task>): Promise<Task>;

  /**
   * Delete a task by id.
   *
   * @param id - Task id
   */
  delete(id: string): Promise<void>;

  /**
   * Link a file to a task.
   *
   * @param taskId - Task id
   * @param fileId - File id
   */
  addFile(taskId: string, fileId: string): Promise<void>;

  /**
   * Unlink a file from a task.
   *
   * @param taskId - Task id
   * @param fileId - File id
   */
  removeFile(taskId: string, fileId: string): Promise<void>;
}
