/**
 * University of La Laguna
 * School of Engineering and Technology
 * Degree in Computer Engineering
 * Final Degree Project (TFG)
 *
 * @author Fabián González Lence <alu0101549491@ull.edu.es>
 * @since March 16, 2026
 * @file domain/enumerations/notification-type.ts
 * @desc Enumeration defining the types of notifications generated by the system.
 * @see {@link https://github.com/alu0101549491/TFG-Fabian-Gonzalez-Lence/tree/main/projects/5-TennisTournamentManager}
 */

/**
 * Represents the type/category of a system notification.
 */
export enum NotificationType {
  /** Match schedule assignment or change. */
  MATCH_SCHEDULED = 'MATCH_SCHEDULED',
  /** Match result has been recorded. */
  RESULT_RECORDED = 'RESULT_RECORDED',
  /** Registration status change (confirmed, rejected, waitlisted). */
  REGISTRATION_UPDATE = 'REGISTRATION_UPDATE',
  /** Tournament status change (started, completed, cancelled). */
  TOURNAMENT_UPDATE = 'TOURNAMENT_UPDATE',
  /** New announcement published. */
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  /** Draw/bracket has been generated or updated. */
  DRAW_PUBLISHED = 'DRAW_PUBLISHED',
  /** Sanction or penalty applied. */
  SANCTION_APPLIED = 'SANCTION_APPLIED',
  /** Payment confirmation or reminder. */
  PAYMENT_UPDATE = 'PAYMENT_UPDATE',
  /** General system notification. */
  SYSTEM = 'SYSTEM',
}

/**
 * Type guard to check if a value is a valid NotificationType.
 *
 * @param value - The value to check
 * @returns True if the value is a valid NotificationType
 */
export function isValidNotificationType(value: unknown): value is NotificationType {
  return Object.values(NotificationType).includes(value as NotificationType);
}

/** Array of all notification types for iteration. */
export const ALL_NOTIFICATION_TYPES = Object.values(NotificationType);
